[project]
name = "hitsz-connect-verge"
version = "0.1.0"
description = "A GUI for connecting to the HITSZ Verge network."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyinstaller>=6.11.1",
    "pyside6>=6.8.1.1",
    "pyside6-fluent-widgets>=1.7.4",
    "requests>=2.32.3",
]
